name: Debug with SSH <img src=A>

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubicloud-standard-4
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH access
        uses: ubicloud/ssh-runner@v1
        with:
          public-ssh-key: "$(id)"
          wait-minutes: 30
      
      # Your other steps here
      # The workflow will wait for the configured minutes after running all steps
