name: Debug with SSH

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubicloud-standard-4
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH access
        uses: ubicloud/ssh-runner@v1
        with:
          public-ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBOfs/E4FVo23aeq3V9S7vy6nPO/ebzUShRDLmcvA1p9"
          wait-minutes: 30
      
      # Your other steps here
      # The workflow will wait for the configured minutes after running all steps
